base_url = "https://ceskoslov.github.io"
title = "Ceskoslov"
description = "Notes from ..."
default_language = "en"
compile_sass = false
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml"]
generate_sitemap = true
generate_robots_txt = true

taxonomies = [
  { name = "tags", feed = true }
]

[markdown]
smart_punctuation = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false

[markdown.highlighting]
style = "inline"
theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
author = "ceskoslov"
author_bio = "Sirens,,,"
github_username = "ceskoslov"
